In [11]:
import pandas as pd
import numpy as np

# Read album information
df_album = pd.read_csv('.\\kaggle_songs.csv')
df_album.head()
df_album.drop(df_album.columns[[0, 1]], axis=1, inplace=True)
df_album.head()

               songid  songno
0  SOAAADD12AB018A9DD       1
1  SOAAADE12A6D4F80CC       2
2  SOAAADF12A8C13DF62       3
3  SOAAADZ12A8C1334FB       4
4  SOAAAFI12A6D4F9C66       5

In [12]:
# Read the track information
df_tracks = pd.read_csv('.\\unique_tracks.csv',encoding = "ISO-8859-1")
df_tracks.head()
df_tracks.drop(df_tracks.columns[[0]], axis=1, inplace=True)
df_tracks.head()

              trackid              songid        artistname           songname
0  TRMMMYQ128F932D901  SOQMMHC12AB0180CB8  Faster Pussy cat       Silent Night
1  TRMMMKD128F425225D  SOVFVAK12A8C1350D9  Karkkiautomaatti        Tanssi vaan
2  TRMMMRX128F93187D9  SOGTUKN12AB017F4F1    Hudson Mohawke  No One Could Ever
3  TRMMMCH128F425532C  SOBNYVR12A8C13558C       Yerba Brava      Si Vos Querés
4  TRMMMWA128F426B589  SOHSBXH12A8C13B0DF        Der Mystic   Tangle Of Aspens

In [13]:
# Read the artist information
df_artist = pd.read_csv('.\\unique_artists.csv',encoding = "ISO-8859-1")
df_artist.drop(df_artist.columns[[0]], axis=1, inplace=True)
df_artist.head()

,artist_id,artisit_mbid,track_title,artistname
0,AR002UA1187B9A637D,7752a11c-9d8b-4220-ac44-e4a04cc8471d,TRMUOZE12903CDF721,The Bristols
1,AR003FB1187B994355,1dbd2d7b-64c8-46aa-9f47-ff589096d672,TRWDPFR128F93594A6,The Feds
2,AR006821187FB5192B,94fc1228-7032-4fe6-a485-e122e5fbee65,TRMZLJF128F4269EAC,Stephen Varcoe/Choir of King's College_ Cambri...
3,AR009211187B989185,9dfe78a6-6d91-454e-9b95-9d7722cbc476,TRMGURO12903CAE2F0,Carroll Thompson
4,AR009SZ1187B9A73F4,8cd574c0-b9f7-4998-94f4-654dffaecdf2,TRGWWFP12903CE7E79,Gorodisch

In [14]:
# Read the evaluation file
df_playcnt = pd.read_csv('.\\kaggle_visible_evaluation_triplets.txt', sep="\t", header=None)
df_playcnt.columns = ["userid", "songid", "playcount"]

# Remove songs with play count greater than 3 (treat them as noise, since they are not very common)
df_playcnt = df_playcnt.loc[df_playcnt['playcount'] <= 3]
df_playcnt.head()
df_playcnt.shape
unique_users = df_playcnt['userid'].unique()
print("User count after reducing play count = {}".format(len(unique_users)))
#df_playcnt['playcount'].describe()

User count after reducing play count = 109036

In [15]:
catalog_prep=pd.merge(pd.merge(df_album, df_tracks, on='songid'),df_artist, on='artistname')
catalog_set= pd.merge(catalog_prep,df_playcnt, on='songid')
catalog_set.head()

,songid,songno,trackid,artistname,songname,artist_id,artisit_mbid,track_title,userid,playcount
0,SOCWIIE12A6701D627,45936,TRFPRAV128E078DB13,Dave Edmunds,Sweet Little Rock And Roller,ARAOAKL1187FB4F2FD,ec4b6d29-527c-4cc0-89bb-8a4775f350d0,TRMSOKU128F930064A,c8c4195f93f75773c984035d330fabce9df1628f,1
1,SODCYYY12A6701D623,50068,TROEWNP128E078DB0F,Dave Edmunds,So Unkind,ARAOAKL1187FB4F2FD,ec4b6d29-527c-4cc0-89bb-8a4775f350d0,TRMSOKU128F930064A,2f22e184cfc40b48704d33aa4f10189ab7924d2b,2
2,SODCYYY12A6701D623,50068,TROEWNP128E078DB0F,Dave Edmunds,So Unkind,ARAOAKL1187FB4F2FD,ec4b6d29-527c-4cc0-89bb-8a4775f350d0,TRMSOKU128F930064A,13da1961e5bb29b77d314bac603e78303a73570a,1
3,SODCYYY12A6701D623,50068,TROEWNP128E078DB0F,Dave Edmunds,So Unkind,ARAOAKL1187FB4F2FD,ec4b6d29-527c-4cc0-89bb-8a4775f350d0,TRMSOKU128F930064A,8ca95fde3249689a5f7d0f75a6380d3d57b17cb3,1
4,SOLCOCH12A81C2301A,175192,TROKXYM128F4236B82,Dave Edmunds,Bad Is Bad (LP Version),ARAOAKL1187FB4F2FD,ec4b6d29-527c-4cc0-89bb-8a4775f350d0,TRMSOKU128F930064A,ec896dc868ed7e25a07f479b0ec592e727f26c12,1

In [16]:
# Get filtered American artists
df_artist_filtered = pd.read_csv('.\\Filtered_Artists.csv',encoding = "ISO-8859-1", header=None)
df_artist_filtered.columns = ["artistname"]
df_artist_filtered.head()

       artistname
0   Jay Boy Adams
1  Chris Akinyemi
2            Akon
3    Michael Alig
4   Johnnie Allan

In [17]:
# Final Data Frame to work from (containing song, artist and the play count)
final_df= pd.merge(catalog_set,df_artist_filtered, on ='artistname')
print(final_df.shape)
final_df.head()
#temp = final_df_[final_df['songid'] == None]

(21570, 10)

,songid,songno,trackid,artistname,songname,artist_id,artisit_mbid,track_title,userid,playcount
0,SOAAYAR12AB018C987,573,TRJVOHN12903CD299B,Wilbert Harrison,Kansas City,ARVVOPC1187FB5C450,4d12dcc2-ab89-4f68-aa7b-0939a839a068,TRMPZAN128F424472C,6a63825295cd1c9ad18d6d9b75403913f396b9be,2
1,SOAAYAR12AB018C987,573,TRJVOHN12903CD299B,Wilbert Harrison,Kansas City,ARVVOPC1187FB5C450,4d12dcc2-ab89-4f68-aa7b-0939a839a068,TRMPZAN128F424472C,36bd7f3bbabaa497fb62cedece641835a8b3f372,1
2,SOAAYAR12AB018C987,573,TRJVOHN12903CD299B,Wilbert Harrison,Kansas City,ARVVOPC1187FB5C450,4d12dcc2-ab89-4f68-aa7b-0939a839a068,TRMPZAN128F424472C,0b2e37ab4bf4485517d6b07f3f1e06ceea3e9c52,1
3,SOAAYAR12AB018C987,573,TRJVOHN12903CD299B,Wilbert Harrison,Kansas City,ARVVOPC1187FB5C450,4d12dcc2-ab89-4f68-aa7b-0939a839a068,TRMPZAN128F424472C,801146152b4f2a5690b2df45e4b20b34c4225ff7,2
4,SOAAYAR12AB018C987,573,TRJVOHN12903CD299B,Wilbert Harrison,Kansas City,ARVVOPC1187FB5C450,4d12dcc2-ab89-4f68-aa7b-0939a839a068,TRMPZAN128F424472C,524f9d3ee79ed73e464bf101d2394400a1fb368a,1

In [18]:
catalog_train = final_df.copy(deep = True)
catalog_train.to_csv("rahul_train", encoding='utf-8', index=False)
print("written_to_rahul_train")

written_to_rahul_train

In [19]:
# Prepare the Item Matrix
item_matrix_prep=catalog_train.groupby(['songid','artistname'],as_index=False)
item_matrix_prep=item_matrix_prep.aggregate(np.sum)
item_matrix = pd.get_dummies(item_matrix_prep[['songid','artistname']], columns=['artistname'],prefix=[None])
item_matrix.shape
print("song matrix = {}".format(item_matrix.shape))
item_matrix.head()
#f = open('item_artist.txt','w')
#f.write(str(item_matrix.columns.values))
#f.close()

song matrix = (1449, 198)

,songid,Aaron Carter,Abra Moore,Adam Lambert,Akon,Al Green,Amii Stewart,Andy Williams,Anita Ward,Annet Artani,...,Tynisha Keli,Tyrone Wells,Vernon Dalhart,Vic Dana,Vienna Teng,Vonda Shepard,Wendy Moten,Wilbert Harrison,Yvonne De Carlo,Yvonne Elliman
0,SOAAYAR12AB018C987,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,SOABDAE12A6701E3FD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,SOABQJR12AB018542E,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,SOABQLD12A8C13C73A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,SOACHLW12AB018C74F,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
# Prepare the User Matrix
user_matrix_prep=catalog_train.groupby(['userid','artistname'],as_index=False)
user_matrix_prep=user_matrix_prep.aggregate(np.sum)
user_matrix = pd.pivot_table(user_matrix_prep, values='playcount', index='userid', columns=['artistname'], aggfunc=np.sum,fill_value=0)
user_matrix.shape
print("User matrix = {}".format(user_matrix.shape))
user_matrix.head()

#f = open('user_artist.txt','w')
#f.write(str(user_matrix.columns.values))
#f.close()

User matrix = (14065, 197)

artistname,Aaron Carter,Abra Moore,Adam Lambert,Akon,Al Green,Amii Stewart,Andy Williams,Anita Ward,Annet Artani,April Stevens,...,Tynisha Keli,Tyrone Wells,Vernon Dalhart,Vic Dana,Vienna Teng,Vonda Shepard,Wendy Moten,Wilbert Harrison,Yvonne De Carlo,Yvonne Elliman
userid,,,,,,,,,,,,,,,,,,,,,
00020fcd8b01986a6a85b896ccde6c49f35142ad,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0003798d61a8010dbfd8010180b7107cbbb8a649,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0003d5245414b9c6244046543a06f601bfc97949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00040e91f2f614ca2f94ebc558dd0fc53ea2b875,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0006a8a3733a7009f8bc109ccb3cdb59a19721ad,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
# Normalize User Play Count information
user_normalized= (user_matrix - user_matrix.values.min()) / (user_matrix.values.max() - user_matrix.values.min())
user_normalized.head()
user_normalized.columns
print("User matrix = {}".format(user_normalized.shape))
user_normalized.head()
user_normalized.to_csv("rahul_user_normalized.csv", encoding='utf-8', index=False)

User matrix = (14065, 197)

In [ ]:
# In[80]:

# Create 2 item matrices, one that has cosine = 0.0, and the other has nothing in it.
item_mat_cpy= item_matrix.copy(deep=True)
item_mat_cpy['cosine'] =0.0
item_mat_cpy.head()
# Drop the song id column
item_matrix_same_shape = item_matrix.drop(item_matrix.columns[[0]], axis=1)
item_matrix_same_shape.head()    
item_matrix_same_shape.shape
item_matrix_same_shape.columns
print("Item Matrix same shape = {}".format(item_matrix_same_shape.shape))
item_matrix_same_shape.head()
item_matrix_same_shape.to_csv("rahul_item_matrix_same_shape.csv", encoding='utf-8', index=False)

In [ ]:
# In[89]:

user_song_mat=catalog_train[['userid','songid']]
# We make a copy so we can set a column to 1
user_song_mat = user_song_mat.copy(deep = True)
user_song_mat['val'] =1
user_song_mat=pd.pivot_table(user_song_mat, 'val', 'userid', 'songid', aggfunc='sum', fill_value=0)
user_song_mat.head()
#user_song_mat.shape

In [ ]:

# In[ ]:
# Compute the Cosine Similarity Matrix between user and song. Unfortunately this is a  4-5 hour process. Therefore, we decided to comment
# the code here. The result of running this code (that is the cosine matrix) has been written to the file rahul_recommendation_final_2_top_all.csv
# which is in the directory of this notebook and the next cell directly loads this file into memory.
# Unfortunately we cannot use the multi line comment approach by Python since it is not recognized by the notebook environment
# so we had to comment line by line.

#df_output = pd.DataFrame(index= range(1),columns=['userid','songid','cosine'])
#df_output = df_output.fillna(0) # with 0s rather than NaNs
#print("Columns = {}".format(df_output))
#from scipy.spatial.distance import cosine


#user_index = 0
#count = 0

#for i in range(0,len(user_normalized.index)-1):
#    import time
#    start = time.clock()
#    for j in range(0,len(item_matrix_same_shape.index)-1):        
#        item_mat_cpy.at[j, 'cosine'] = 1 - cosine(item_matrix_same_shape.iloc[j], user_normalized.iloc[i])
#    end = time.clock()
#    diff = end - start
#    user_index += 1
#    print("finished user = {}, time difference ={}".format(user_index, diff))
#    df_tmp=item_mat_cpy[['songid','cosine']]
#    df_tmp['userid'] = user_normalized.index[i]
#    df_output=df_output.append(df_tmp)
#    item_mat_cpy['cosine'] =0.0
    
#df_output.head()
#print("coumns = {}".format(df_output.columns))
#df_output.to_csv("rahul_recommendation_final_all_testing_only_crap_1.csv", encoding='utf-8', index=False)
#print(df_output)

In [ ]:
# This cell loads the cosine matrix from the file rahul_recommendation_final_2_top_all.csv. This cosine matrix was prepared
# as an offline process and written to this file since preparing the cosine matrix is a 4-5 hour process.

#df_output.head()
print("start")
recommendation = pd.DataFrame.from_csv("rahul_recommendation_final_2_top_all.csv", encoding='utf-8', index_col=None)
recommendation.head()
#print(recommendation.index)
#print(recommendation.columns.tolist())
#print(type(recommendation))
print("done")

In [ ]:
# This cell calculates the information needed to calculate the average recall. 
# To get the recall we need to know the entire list of songs that the user listened (the entire truth) and the list of songs we
# predict the user would listen (so the count of the values greater than 0.5)

user_recall = {}
print(recommendation.columns.tolist())
print(type(recommendation))

for index, entry in recommendation.iterrows():
    user_id = entry["userid"]
    song_id = entry["songid"]
#    print("at index = {}".format(index))
    cosine_value = entry["cosine"]
    if not user_id in user_recall:
        user_recall[user_id] = {'truth':0, 'prediction':0}
    if cosine_value != 0:
        user_recall[user_id]['truth'] += 1
        if cosine_value > 0.5:
            user_recall[user_id]['prediction'] += 1
#        else:
#            print("found something!: {}".format(user_id))
print("Calculated information for recall")
print(user_recall)

In [ ]:
# This cell also writes the information needed to calculate average user recall to a file since the process takes a lot of time
# because the user song combination is so large.
import json
with open('user_recall.txt', 'w') as file:
     file.write(json.dumps(user_recall)) # use `json.loads` to do the reverse
print("done")

In [ ]:
print(user_recall)

In [ ]:
# This cell calculates the recall per user, and then uses that to calculate the average recall for all users.

print("Recall per user:")
total_recall = 0
for user_id, value in user_recall.items():
    if user_recall[user_id]['truth'] == 0:
        user_recall[user_id]['truth'] = 1
    recall = user_recall[user_id]['prediction']/user_recall[user_id]['truth']
#    print("recall = {}".format(recall * 100))
    total_recall += recall
print("Average User Recall = {} %".format(total_recall/len(user_recall) * 100))

In [ ]:
# To calculate the precision we would like to develop a dictionary where the key is the user id, and the value is another dictionary, 
# where the key is the song id, and the value is the cosine value between the user and that song.
# This makes precision calculations easier.

user_recommendation = {}
#print("prepare dictionary")
count_position = 0
for index, row in recommendation.iterrows():
    user_id = row["userid"]
    song_id = row["songid"]
    cosine = row["cosine"]
#    if index == 50000:
#        break
#    print("index = {}, user_id = {}, song id = {}".format(index, user_id, song_id))
    if not user_id in user_recommendation:
        user_recommendation[user_id] = {}
    # There is only one song per user record (we don't recommend same song twice)
    user_recommendation[user_id][song_id] = cosine

print("Prepared the dictionary")
print(user_recommendation)

In [ ]:
print(len(user_recommendation))

In [ ]:
import json
with open('user_recommendation_hashtable.txt', 'w') as file:
     file.write(json.dumps(user_recommendation)) # use `json.loads` to do the reverse
print("done")

In [ ]:
# In this cell, we calculate the precision @3, @5, @10 for every user, and then average that to get the average value.


count_recommended = {}
k_values = [3,5,10] 
user_precision = {}
user_statistic = {}
row_results = []
import operator
total_precision_3 =0
total_precision_5 =0
total_precision_10 = 0
cols = ['userid', '3','5','10']
result = pd.DataFrame(columns = cols, index = None)

position = 0
for i, (key, value) in enumerate(user_recommendation.items()):
# now value = the list of songs and their cosine values for the user of id = key

#    print("at index = {}, user = {}, value  = {}".format(i, key, value))
    if i == 0:
        continue
    position += 1
    # Get the top 10 songs we would recommend, in decreasing order of cosine values for the user of id = key
    top_10_recommended = sorted(value.items(),key = operator.itemgetter(1),reverse = True)[0:10]
#    print("recommended top 10 recommended: {}\n\n".format(top_10_recommended))
#    print("user ud = {}".format(key))

    # Get the actual songs the user listened to.
    actual_top = final_df[final_df['userid'] == key]
#    print("length of top = {}".format(len(actual_top)))
    
    # Top 3 songs we recommend
    top_3 = dict(top_10_recommended[0:3])
    
    # Top 5 songs we recommend
    top_5 = dict(top_10_recommended[0:5])
    
    # Top 10 songs we recommend
    top_10 = dict(top_10_recommended)
#    print("top 5:")
#    print(top_5)
#    print("top 10:")
#    print(top_10)
#    print("top 3:")
#    print(top_3)
    present_3 = 0
    present_5 = 0
    present_10 = 0
    
#    print("these are the songs")
    for index, row in actual_top.iterrows():
#        if key == "0003d5245414b9c6244046543a06f601bfc97949":
#            print(row["songid"])
        if row["songid"] in list(top_10.keys()):
            present_10 += 1 # track how many of the top 10 songs we recommend the user has actually heard.
        if row["songid"] in list(top_3.keys()):
            present_3 += 1 # track how many of the top 3 songs we recommend the user has actually heard.
        if row["songid"] in list(top_5.keys()):
            present_5 += 1 # track how many of the top 5 songs we recommend the user has actually heard.
    
    
    if not user_id  in user_precision:
        user_precision[key] = {}
        
        
    # You can ignore the calculation regarding user_statistic.
    if not 3 in user_statistic:
        user_statistic[3] = 0
        
    if not 5 in user_statistic:
        user_statistic[5] = 0
        
    if not 10 in user_statistic:
        user_statistic[10] = 0

    if present_3 == 3:
        user_statistic[3] += 1
    
    if present_5 == 5:
        user_statistic[5] += 1

    if present_10 == 10:
        user_statistic[10] += 1
        
    # Calculate precision @3, @5, @10
    precision_3 = float(present_3/3.0)
    total_precision_3 += precision_3
    precision_5 = float(present_5/5.0)
    total_precision_5 += precision_5
    precision_10 = float(present_10/10.0)
    total_precision_10 += precision_10
    
    user_precision[key] = {'userid': key, '3':precision_3, '5':precision_5, '10':precision_10}
    
    #result.iloc[position] = [key, float(present_3/3.0), float(present_5/5), float(present_10/10.0)]
    #row.append(user_precision[key])
    row_results.append(pd.Series([key, float(present_3/3.0), float(present_5/5), float(present_10/10.0)]))
    
    print("precision = {},{}, {}".format(user_precision[key]['3'], user_precision[key]['5'], user_precision[key]['10']))

# Calculate the average user precision
print("total at3 = {}, at 5 = {} at 10 = {}".format(total_precision_3/len(user_precision), total_precision_5/len(user_precision), total_precision_10/len(user_precision)))
print("results..")
#print(user_precision)